graphhopper:
  datareader.file: southern-zone-251215.osm.pbf
  graph.location: graph-cache

  ch.disable: true

  import.osm.ignored_highways:
    - footway
    - cycleway
    - bridleway
    - steps
    - path
    - corridor
    - proposed
    - construction

  encoded_values:
    - car_access
    - car_average_speed
    - foot_access
    - foot_average_speed

  profiles:
    - name: car
      custom_model_files:
        - drc_car.json

    - name: foot
      custom_model_files:
        - drc_foot.json

server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8990
